services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: genai-server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: genai-client
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server
