name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20] # always use latest LTS for JS projects

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (backend)
        run: |
          cd server
          npm install

      - name: Run lint (backend)
        run: |
          cd server
          npm run lint || echo "No lint script defined, skipping"

      - name: Run tests (backend)
        run: |
          cd server
          npm test || echo "No tests defined, skipping"

      - name: Install dependencies (frontend)
        run: |
          cd client
          npm install

      - name: Run lint (frontend)
        run: |
          cd client
          npm run lint || echo "No lint script defined, skipping"

      - name: Run tests (frontend)
        run: |
          cd client
          npm test || echo "No tests defined, skipping"

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: github.ref == 'refs/heads/main' # Only build Docker image on main branch merges

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/genai-saas:latest
