name: Daily Usage Reset (IST)

on:
  schedule:
    # 00:00 IST = 18:30 UTC daily
    - cron: "30 18 * * *"
  workflow_dispatch: {}

jobs:
  call-reset-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call reset-limits endpoint
        run: |
          set -e
          echo "Calling: $CRON_ENDPOINT"
          HTTP_CODE=$(curl -s -o /tmp/resp.txt -w "%{http_code}" \
            -X POST "$CRON_ENDPOINT" \
            -H "x-cron-secret: $CRON_SECRET")
          echo "HTTP $HTTP_CODE"
          cat /tmp/resp.txt
          if [ "$HTTP_CODE" -lt 200 ] || [ "$HTTP_CODE" -ge 300 ]; then
            exit 1
          fi
        env:
          CRON_ENDPOINT: ${{ secrets.CRON_ENDPOINT }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
